apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eventgenerator
  labels:
    app: eventgenerator
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: eventgenerator
      labels:
        app: eventgenerator
    spec:
      containers:
      - name: eventgenerator
        image: eu.gcr.io/census-gcr-int/census-event-generator:0.3.0-rc.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "1024Mi"
          limits:
            cpu: "1.0"
            memory: "2048Mi"
        readinessProbe:
          httpGet:
            path: /info
            port: 8171
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /info
            port: 8171
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        ports:
        - name: http-server
          containerPort: 8171
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Dlogging.useJson=true
            -Dspring.profiles.active=performance
            -Dlogging.level.uk.gov.ons.ctp=WARN
            -Dlogging.level.org.springframework=WARN
            -Dendpoints.autoconfig.enabled=false-Dendpoints.beans.enabled=false
            -Dendpoints.configprops.enabled=false
            -Dendpoints.dump.enabled=false
            -Dendpoints.env.enabled=false
            -Dendpoints.metrics.enabled=false
            -Dendpoints.mapping.enabled=false
            -Dendpoints.shutdown.enabled=false
            -Dendpoints.trace.enabled=false
            -Dmanagement.health.rabbit.enabled=false"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbit-identity
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit-identity
              key: password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: event-generator-config
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: event-generator-config
              key: rabbitmq-port
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: event-generator-identity
              key: username
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: event-generator-identity
              key: password
